--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    facing: front
    service: wordpuzzlewordfinder
    type: mongo
  name: wpwf-mongo
spec: 
  ports: 
    - 
      name: mongo
      port: 27017
      protocol: TCP
      targetPort: mongo
  selector: 
    name: wpwf-mongo
