--- 
apiVersion: v1
kind: ReplicationController
metadata: 
  labels: 
    facing: front
    service: wordpuzzlewordfinder
    type: rails
  name: wpwf-rails
spec: 
  replicas: 2
  selector: 
    name: wpwf-rails
  template: 
    metadata: 
      labels: 
        name: wpwf-rails
    spec: 
      containers: 
        - 
          env: 
            - 
              name: MONGODB_ENV_TUTUM_SERVICE_HOSTNAME
              value: wpwf-mongo
            - 
              name: MONGODB_PORT_27017_TCP_PORT
              value: "27017"
          image: quay.io/purplebooth/wordpuzzlewordfinder
          imagePullPolicy: Always
          livenessProbe: 
            httpGet: 
              path: /dictionary?mask=%21%21
              port: 3000
            initialDelaySeconds: 15
            timeoutSeconds: 1
          name: wpwf-rails
          ports: 
            - 
              containerPort: 3000
              name: http
              protocol: TCP
      restartPolicy: Always
