--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    facing: front
    service: wordpuzzlewordfinder
    type: rails
  name: wpwf-rails
spec: 
  ports: 
    - 
      name: http
      port: 3000
      protocol: TCP
      targetPort: http
  selector: 
    service: wordpuzzlewordfinder
    type: rails
