defaults: &defaults
  host: <%= ENV['MONGO_PORT_27017_TCP_ADDR'] %>
  port: <%= ENV['MONGO_PORT_27017_TCP_PORT'] %>

development:
  <<: *defaults
  database: scrabble_development

test:
  <<: *defaults
  database: scrabble_test

# set these environment variables on your prod server
production:
  <<: *defaults
  database: scrabble_prod