defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: scrabble_development

test:
  <<: *defaults
  database: scrabble_test

# set these environment variables on your prod server
production:
  <<: *defaults
  database: scrabble
  uri: <%= ENV['MONGOHQ_URL'] %>
  username: <%= ENV['MONGO_USERNAME'] %>
  password: <%= ENV['MONGO_PASSWORD'] %>
