
development:
  hosts:
    - <%= ENV['MONGODB_HOST_1'] %>
    - <%= ENV['MONGODB_HOST_2'] %>

  username: <%= ENV['MONGODB_USERNAME'] %>
  password: <%= ENV['MONGODB_PASSWORD'] %>
  database: <%= ENV['MONGODB_DATABASE'] %>


test:
  uri: <%= ENV['MONGODB_URI'] %>

production:
  hosts:
    - "<%= ENV['MONGODB_HOST_1'] %>"
    - "<%= ENV['MONGODB_HOST_2'] %>"

  username: <%= ENV['MONGODB_USERNAME'] %>
  password: <%= ENV['MONGODB_PASSWORD'] %>
  database: <%= ENV['MONGODB_DATABASE'] %>
